name: Creating a new release

on:
  push:
    branches:
      - main

jobs:
  quality-checks:
    name: Quality checks
    uses: ./.github/workflows/validation_workflow.yml

  releasing:
    name: Releasing
    runs-on: ubuntu-latest
    needs: quality-checks
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: Install dependencies
        run: npm ci

      - name: Create Release
        run: npx semantic-release