name: Unit tests

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: App setup
        run: npm install

      - name: Run unit tests
        run: |
          npm run test
